/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;

import databases.DatabaseConnection;
import Storage.HotelListModel;
import Model.SearchList;
import JFrame.Search;
import java.awt.List;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.xml.datatype.DatatypeConfigurationException;
import Model.Hotel;
import Model.Room;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author marinmcginley
 */
public class Index extends javax.swing.JFrame {


    private LogIn logIn;
    
    private ArrayList<Hotel> aviableHotelList;
    DefaultTableModel model;
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        
        aviableHotelList = new ArrayList<Hotel>();
        jTable.getTableHeader().setPreferredSize(new Dimension(10,35)); // stilli breidd og hæð á column head
        model = (DefaultTableModel) jTable.getModel();
        
        // Gera hnapp ósýnilega
        jLogOut.setVisible(false);
    }
    
    public void putListInTable(ArrayList<Hotel> hotelList) {
        //Object[] row = new Object[11];
        
        for(int i=0; i<hotelList.size(); i++) {
            ArrayList<Room> hotelsRooms = hotelList.get(i).viewRooms();
            for(int j=0; j<hotelsRooms.size(); j++) {
                String hotelName = hotelList.get(i).getNameOfHotel();
                String location = hotelList.get(i).getLocationOfHotel();
                int price = hotelsRooms.get(j).getPriceForNight();
                int grade = 0;
                int NumberOfGrownup = hotelsRooms.get(j).getNumberOfAdults();
                int numberOfChildren = hotelsRooms.get(j).getNumberOfChildren();
                boolean handic = hotelList.get(i).getAviableForHandic();
                boolean gym = hotelList.get(i).getGym();
                boolean swimmingpool = hotelList.get(i).getSwimmingPool();
                boolean wifi = hotelList.get(i).getWifi();
                boolean pickup = hotelList.get(i).getPickUp();
                boolean breakfast = hotelList.get(i).getBreakfastIncluded();
                model.addRow(new Object[]{hotelName,location,price,grade,NumberOfGrownup,numberOfChildren,handic,gym,swimmingpool,wifi,pickup,breakfast});
            }
        }
    }


    public void initializeAfterLogIn() {

        jLogIn.setVisible(false);
        jRegister.setVisible(false);
        
        jLogOut.setVisible(true);
        jUserName.setText(logIn.getUserName());
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jText = new javax.swing.JLabel();
        jLogIn = new javax.swing.JButton();
        jRegister = new javax.swing.JButton();
        jSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLogOut = new javax.swing.JButton();
        jUserName = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jText.setText("Velkomin inná forritið okkar.  Hér getur þú leita að hóteli á Íslandi :");

        jLogIn.setText("Innskráning");
        jLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogInActionPerformed(evt);
            }
        });

        jRegister.setText("Nýskráning");
        jRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterActionPerformed(evt);
            }
        });

        jSearch.setText("Byrja leit");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hotel", "Staðsetning", "Verð", "Einkunn", "<html>Fjöldi<br>fullorðna</html>", "Fjöldi barna", "<html>Aðfengi fyrir<br> hreyfihamlaða</html>", "Ræktin", "Sundlaug", "WIFI", "<html>Aksturs-<br>þjónusta</btml>", "<html> Morgunmatur<br> innifalinn</html>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.setColumnSelectionAllowed(true);
        jTable.setGridColor(new java.awt.Color(255, 255, 255));
        jTable.setRowHeight(20);
        jTable.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jTable.setSelectionForeground(new java.awt.Color(255, 51, 204));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLogOut.setText("Útskráning");
        jLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLogIn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jText)
                .addGap(150, 150, 150)
                .addComponent(jUserName)
                .addGap(63, 63, 63)
                .addComponent(jLogOut))
            .addGroup(layout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addComponent(jSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLogIn)
                    .addComponent(jRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jText)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLogOut)
                        .addComponent(jUserName)))
                .addGap(18, 18, 18)
                .addComponent(jSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        Search search = null;
        
        if (logIn == null) {
            search = new Search(this, true, "");
        } else {
            search = new Search(this, true, logIn.getUserName());
        }

        search.setVisible(true);
        
        // útvega svo eins og í AdalDagra.java í Dagska verkefninu.
        // Ef isVista() == true þá birtum við lista af hótelum fyrir neðan
        
        if(search.isVista() == true) {
            SearchList s = new SearchList();
            String nafnHotel = search.searchGetHotelName();
            String location = search.searchGetLocation();
            int gradeFrom = search.searchGetGradeFrom();
            int gradeTo = search.searchGetGradeTo();
            int priceFrom = search.searchGetPriceFrom();
            int priceTo = search.searchGetPriceTo();
            if(gradeTo == -1) {
                gradeTo = 1000000; // stilli sem eitthvað mjög stórt;
            }
            String wifi = search.searchGetWifi();
            String handic = search.searchGetHandic();
            String pickUp = search.searchGetPickup();
            String breakfast =search.searchGetBreakfast();
            String swimming = search.searchGetSwimmingpool();
            String gym = search.searchGetGym();

            ArrayList<Hotel> hotelList = s.getHotel("SELECT * FROM Hotel WHERE nameOfHotel LIKE '%" + nafnHotel + "%'"
                    + " AND location LIKE '%" + location +"%'"
                    + " AND aviableForHandic LIKE '%" + handic + "%'"
                    + " AND gym LIKE '%" + gym + "%'"    
                    + " AND swimmingPool LIKE '%" + swimming + "%'"
                    + " AND wifi LIKE '%" + wifi + "%'"
                    + " AND pickUp LIKE '%" + pickUp + "%'"
                    + " AND breakfastIncluded LIKE '%" + breakfast + "%'"        
                    + " AND grade > " + gradeFrom + " AND grade < " + gradeTo);
            System.out.println("size og hotelList : " + hotelList.size());
            putListInTable(hotelList);
        }
        //setModel(aviableHotelList);
    }//GEN-LAST:event_jSearchActionPerformed

    private void jLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogInActionPerformed
        logIn = new LogIn(this, true);  
        logIn.setVisible(true);
        if (logIn.getUserName() != null) {
            initializeAfterLogIn();
        }
    }//GEN-LAST:event_jLogInActionPerformed

    private void jRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterActionPerformed
        Register nyskraning = null;
        
        nyskraning = new Register(this, true);
        
        nyskraning.setVisible(true);
    }//GEN-LAST:event_jRegisterActionPerformed

    private void jLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutActionPerformed
        logIn = null;
        jLogOut.setVisible(false);
        jUserName.setText(null);
        
        jLogIn.setVisible(true);
        jRegister.setVisible(true);
    }//GEN-LAST:event_jLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*DatabaseConnection connection = new DatabaseConnection();
        connection.connect();*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jLogIn;
    private javax.swing.JButton jLogOut;
    private javax.swing.JButton jRegister;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearch;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jUserName;
    // End of variables declaration//GEN-END:variables
}
